### ISSUE TITLE
Cannot install package via cabal with base 4.14 because of constraint in .cabal

### ISSUE THREAD

**Issue by gdupont1** [diagrams/monoid-extras#43]
Hello,

Installing the package via cabal with a recent installation (base 4.14) does not work.
I think this comes from the `base>=4.7 && <4.14` constraint in the `.cabal` file.
I managed to build master with my installation, so my guess is that the constraint can be relaxed; note however that 
Maybe switch for `base==4.*` (made available in cabal 1.6)?

Many thanks,
Guillaume.

**Comment by byorgey** [comment]
Thanks for reporting this!  We have not yet upgraded everything to work with GHC 8.10, but I'll put it on my list of things to look at soon (once the semester ends in another week and a half or so).

People have different philosophical positions on the use of constraints like `base == 4.*`.  Personally I don't like to do it because I think of it as a promise that the package will definitely work with all possible 4.x versions of base.  Although it's certainly *likely* that the package will continue to work with future base 4.x releases, there's no way to know for sure until they are released.

**Comment by chris-martin** [comment]
It seems to me that this has already been fixed, and just needs a Hackage release? I'm building from the git repo and it seems to work.

**Comment by byorgey** [comment]
Yep, a Hackage release should be coming soon.  Sorry for the delay.

**Comment by chris-martin** [comment]
I know how it goes, thank you for your efforts :smile:
